### ISSUE TITLE
Block Breaking Issues

### ISSUE THREAD

**Issue by JPCyberDude** [RedFox86/Tinkers-Tool-Leveling#1]
When breaking a block it does not break, this issue is not prevalent with vanilla tools even with the mod installed, only levelable tinker's tools.

Small Snippet of Log as proof of issue:

[18:44:50] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@46524253, suppressing error
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:322) ~[?:?]
	at net.redfox.tleveling.leveling.ToolExpHandler.getRandomBonus(ToolExpHandler.java:74) ~[tleveling-0.0.2-1.19.2.jar%23623!/:0.0.2-1.19.2]
	at net.redfox.tleveling.leveling.ToolExpHandler.getExpFromBlockState(ToolExpHandler.java:60) ~[tleveling-0.0.2-1.19.2.jar%23623!/:0.0.2-1.19.2]
	at net.redfox.tleveling.leveling.ToolExpHandler.saveMiningExpOnTool(ToolExpHandler.java:24) ~[tleveling-0.0.2-1.19.2.jar%23623!/:0.0.2-1.19.2]
	at net.redfox.tleveling.leveling.ToolEventHandler.handleMiningEvent(ToolEventHandler.java:16) ~[tleveling-0.0.2-1.19.2.jar%23623!/:0.0.2-1.19.2]
	at net.redfox.tleveling.event.ModEvents$ForgeEvents.onBlockBreak(ModEvents.java:35) ~[tleveling-0.0.2-1.19.2.jar%23623!/:0.0.2-1.19.2]
	at net.redfox.tleveling.event.__ForgeEvents_onBlockBreak_BreakEvent.invoke(.dynamic) ~[tleveling-0.0.2-1.19.2.jar%23623!/:0.0.2-1.19.2]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:633) ~[forge-1.19.2-43.4.0-universal.jar%23642!/:?]
	at slimeknights.tconstruct.library.tools.helper.ToolHarvestLogic.breakBlock(ToolHarvestLogic.java:102) ~[TConstruct-1.19.2-3.8.3.39.jar%23616!/:1.19.2-3.8.3.39]
	at slimeknights.tconstruct.library.tools.helper.ToolHarvestLogic.handleBlockBreak(ToolHarvestLogic.java:233) ~[TConstruct-1.19.2-3.8.3.39.jar%23616!/:1.19.2-3.8.3.39]
	at slimeknights.tconstruct.library.tools.item.ModifiableItem.onBlockStartBreak(ModifiableItem.java:281) ~[TConstruct-1.19.2-3.8.3.39.jar%23616!/:1.19.2-3.8.3.39]
	at net.minecraftforge.common.extensions.IForgeItemStack.onBlockStartBreak(IForgeItemStack.java:132) ~[forge-1.19.2-43.4.0-universal.jar%23642!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:238) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:218) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1024) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23637!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Log:

[latest.log](https://github.com/user-attachments/files/16770350/latest.log)

**Comment by RedFox86** [comment]
Hello,
I had this bug one time while testing, but I thought I fixed it. It basically happens when the BlockBreak event has a bug in it and is therefore canceled. So, I will try to fix it but for now all I can recommend is updating to the latest version and perhaps recreating your tools as the data is stored with NBT.

**Comment by JPCyberDude** [comment]
> Hello, I had this bug one time while testing, but I thought I fixed it. It basically happens when the BlockBreak event has a bug in it and is therefore canceled. So, I will try to fix it but for now all I can recommend is recreating your tools as the data is stored with NBT.
> 
> My fix for now will be to add some checks to ensure that the value that caused the issue is always positive - but it never should have been negative in the first place so I'm not sure how that happened.
> 
> Can I know whether you experienced this issue immediately upon downloading the mod or whether it happened after a little while of playing with it?
> 
> This mod is the first one I've ever made and I only finished it about a week ago, so I hope you can excuse the bugs. Thank you, RedFox86

Thank you for the quick response and explanation, RedFox86. I completely understand that bugs can happen, especially with a new mod. The mod is still mostly usable for me, so I’ll keep an eye out for any updates you release. I appreciate your effort in working on a fix, and I hope you enjoy the process of refining your mod further. Thanks again for your work on this!

**Comment by RedFox86** [comment]
Hello,
I've just rolled out a quick fix for that, and it should solve that issue. You should be able to download it on Modrinth or Curseforge, (version 0.0.3). However, it is just a quick fix and I would like to solve the core problem too.

If possible, could you tell me the scenario in which this bug happened? I can see from the logs that it was upon gaining experience via mining, so a few details would be extremely helpful:
- The block you were breaking
- The tool you were using
- Any mods outside of Tinker's / Mantle
- The frequency of this issue (once in a while, every block, only on certain blocks, etc)

Thank you so much. Your comments help me solve bugs exponentially faster. 
RedFox86

**Comment by JPCyberDude** [comment]
> Hello, I've just rolled out a quick fix for that, and it should solve that issue. You should be able to download it on Modrinth or Curseforge, (version 0.0.3). However, it is just a quick fix and I would like to solve the core problem too.
> 
> If possible, could you tell me the scenario in which this bug happened? I can see from the logs that it was upon gaining experience via mining, so a few details would be extremely helpful:
> 
> * The block you were breaking
> * The tool you were using
> * The frequency of this issue (once in a while, every block, only on certain blocks, etc)
> 
> Thank you so much. Your comments help me solve bugs exponentially faster. RedFox86
> 
> Edit: I've just tried that version of the mod in a creative world with just Tinker's Construct and Mantle, and it appeared to work fine. So my best guess is that it might be a conflict with another mod. While I can try my best to fix that, third party mods are a little difficult to handle.


Thank you, RedFox86, for the quick fix and your continued support!

I've updated to version 0.0.3 and conducted some further testing. Here's what I've observed:

- **Scenario Details**:
  - The issue seems to occur primarily with vanilla blocks, though I've noticed it occasionally with a few modded Nether blocks as well.
  - The problem doesn’t appear to be tied to a specific tool or block type, but rather to certain blocks. Once the issue starts with a particular block and tool combination, it persists.
  - The issue is more noticeable with blocks that are broken instantly, which might be linked to how the experience calculation or the block-breaking event is handled.

- **Potential Causes**:
  - **Experience Calculation**: The method `getExpFromBlockState(BlockState state)` in `ToolExpHandler.java` seems to be where the experience is calculated based on block tags. If a block's experience is incorrectly set or if the experience multiplier is misconfigured, it could result in unexpected behavior during the block-breaking event.
  - **Random Bonus Calculation**: The `getRandomBonus(double amount)` method might be causing issues if the `amount` is zero or negative. This could potentially trigger the error seen in the logs, especially when breaking blocks that provide minimal or no experience.

- **Logs and Environment**:
  - Based on the logs, it seems there might be some interactions with other mods that could be influencing this behavior. There are several warnings related to mixin configurations and rendering issues (particularly with `Rubidium`), which might be worth considering.

I hope this information helps in pinpointing the root cause of the issue. If you need any more details or would like me to test further, please feel free to reach out. Thanks again for your hard work on this mod!

**Comment by RedFox86** [comment]
Thank you. I've found the problem - the Random function nextInt cannot take the value of 0. In my testing, this didn't work because on my version, the blocktag "#all_signs" doesn't exist, and therefore the excluded blocks tag just didn't work in it's entirety. After fixing that, I was able to recreate and fix your issue. If you download the latest version, then I think it should work. Thank you so much for bringing this issue to my attention!

**Comment by JPCyberDude** [comment]
> Thank you. I've found the problem - the Random function nextInt cannot take the value of 0. In my testing, this didn't work because on my version, the blocktag "#all_signs" doesn't exist, and therefore the excluded blocks tag just didn't work in it's entirety. After fixing that, I was able to recreate and fix your issue. If you download the latest version, then I think it should work. Thank you so much for bringing this issue to my attention!

Thank you for the quick fix! I’ve updated to the latest version, and everything seems to be working perfectly now. I really appreciate your dedication to resolving the issue so quickly. Thanks again for all your hard work!
